import { createClient } from "jsr:@supabase/supabase-js@2";
import { dedupeByUrl, mapPost, type SecurityPostRow } from "./mapping.ts";

// ingest-posts
// ------------
// Receives batches of security-alert posts from the external X scraper (nana's
// x-crypto-alerts task) and upserts them into security_posts for the notify pipeline.
//
// Auth: gated on a shared secret (INGEST_API_KEY) sent as the `x-ingest-key` header.
// Deployed with --no-verify-jwt so this header is the only gate — a dedicated secret is
// deterministic (no dependency on which key format the platform injects for the service
// role) and lets the scraper authenticate with just this one key, no anon key needed.
//
// Deploy (run once, values are project-specific — not committed):
//   supabase secrets set INGEST_API_KEY=<random-64-hex>   # generated by us, shared with the scraper
//   supabase functions deploy ingest-posts --use-api --no-verify-jwt --project-ref <ref>

function jsonResponse(body: unknown, status = 200) {
  return new Response(JSON.stringify(body), {
    status,
    headers: { "Content-Type": "application/json" },
  });
}

Deno.serve(async (req) => {
  if (req.method !== "POST") return jsonResponse({ error: "Method not allowed" }, 405);

  const ingestKey = Deno.env.get("INGEST_API_KEY");
  if (!ingestKey || req.headers.get("x-ingest-key") !== ingestKey) {
    return jsonResponse({ error: "Unauthorized" }, 401);
  }

  let body: unknown;
  try {
    body = await req.json();
  } catch {
    return jsonResponse({ error: "Invalid JSON body" }, 400);
  }

  const posts = (body as { posts?: unknown })?.posts;
  if (!Array.isArray(posts)) {
    return jsonResponse({ error: "Body must be { posts: [...] }" }, 400);
  }

  // Map to rows (dropping malformed ones), then dedupe within the batch.
  const mapped: SecurityPostRow[] = [];
  for (const p of posts) {
    const row = mapPost(p);
    if (row) mapped.push(row);
  }
  const rows = dedupeByUrl(mapped);

  if (rows.length === 0) {
    return jsonResponse({ inserted: 0, skipped: posts.length });
  }

  try {
    const admin = createClient(
      Deno.env.get("SUPABASE_URL")!,
      Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!,
    );
    // DO NOTHING on post_url conflict; RETURNING yields only the newly-inserted rows, so
    // their count is `inserted`. Re-sending a batch is safe (the scraper retries by design).
    const { data, error } = await admin
      .from("security_posts")
      .upsert(rows, { onConflict: "post_url", ignoreDuplicates: true })
      .select("post_url");
    if (error) {
      console.error("[ingest-posts] upsert failed", { error: error.message });
      return jsonResponse({ error: `Upsert failed: ${error.message}` }, 500);
    }
    const inserted = data?.length ?? 0;
    // Everything not newly inserted is skipped: malformed + within-batch dupes + already stored.
    return jsonResponse({ inserted, skipped: posts.length - inserted });
  } catch (err) {
    console.error("[ingest-posts] fatal", err);
    return jsonResponse({ error: err instanceof Error ? err.message : "Unknown error" }, 500);
  }
});
